/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2017-11-15 13:40:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.members;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t<title>欢迎注册新鲜e客_新鲜e客（pinnong.com）-通州区网购首选-正品低价、品质保障、配送及时、轻松购物</title>\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"通州酒水,通州生鲜,通州水果,通州蔬菜,通州肉,通州蛋,通州促销活动,通州促销产品,北京通糖烟酒糖业有限公司,北京通州区超市\"/>\r\n");
      out.write("    <meta http-equiv=\"description\" content=\"北京通州酒水,北京通州生鲜,北京通州促销产品等,北京通州区超市连锁,北京通州区免费送货,北京通州区正品低价、品质保障、配送及时、轻松购物,北京通州新鲜e客,北京通州品质\"/>\r\n");
      out.write("    <css>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/pc/register.css\"/>\r\n");
      out.write("    </css>\r\n");
      out.write("\r\n");
      out.write("    <js>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/lib/js/jquery.hoverIntent.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/js/pc/common.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/js/pc/register.js\"></script>\r\n");
      out.write("    </js>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- 导航条 S -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"pull-left text-left\">\r\n");
      out.write("\t\t\t<a href=\"#\"><img src=\"assets/img/pc/logo.png\" width=\"165px\" border=\"0\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 导航条 E -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main green-bg\">\r\n");
      out.write("        <div class=\"container row\">\r\n");
      out.write("            <div class=\"col-sm-6 pull-left\">\r\n");
      out.write("                <img src=\"assets/img/pc/zs_register.png\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 pull-right regisiter-con\">\r\n");
      out.write("                <div class=\"title\">注册账号</div>\r\n");
      out.write("                <form class=\"form-horizontal regisit-wrap-inner\" method=\"post\" id=\"registerForm\" onsubmit=\"return true;\" action=\"members/login.html\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12 errorTip\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-phone\"></span></span>\r\n");
      out.write("                                <input id=\"username\" type=\"text\" name=\"username\" class=\"form-control input-lg\" placeholder=\"手机号\" maxlength=\"11\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("                                <input id=\"password\" type=\"password\" name=\"password\" minlength=\"6\" maxlength=\"20\" class=\"form-control input-lg\" placeholder=\"设置6-20位密码\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("                                <input id=\"rqpwd\" type=\"password\" name=\"rqpwd\" class=\"form-control input-lg\" minlength=\"6\" maxlength=\"20\" equalto=\"#password\" placeholder=\"确认密码\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-text-width\"></span></span>\r\n");
      out.write("                                <input type=\"text\" id=\"verificationCode\" name=\"verificationCode\" class=\"form-control input-lg\" placeholder=\"随机验证码\" maxlength=\"6\"/>\r\n");
      out.write("\r\n");
      out.write("                                <a data-disabled=\"0\" href=\"javascript:void(0);\" class=\"input-group-addon btnSendMessage\"><img src=\"/yzm\" title=\"看不清,换一张\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-text-width\"></span></span>\r\n");
      out.write("                                <input type=\"text\" id=\"dxyzm\" name=\"dxyzm\" class=\"form-control input-lg\" placeholder=\"短信验证码\" maxlength=\"6\"/>\r\n");
      out.write("                                <a data-disabled=\"0\" href=\"javascript:void(0);\" class=\"input-group-addon btnSendMessage\">获取短信验证码</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-md-12 text-left\">\r\n");
      out.write("                            <div class=\"checkbox checked\">\r\n");
      out.write("                                <label>\r\n");
      out.write("                                    <input id=\"ctchk\" type=\"checkbox\" checked=\"\">我已阅读并同意《用户注册协议》\r\n");
      out.write("                                    <a href=\"members/login\" style=\"position: relative;left: 85px;\">立即登录</a>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"space\"></div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <button type=\"submit\" class=\"col-xs-12 btn btn-success btn-lg registerBtn\">立即注册</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
